spring:
  datasource:
    url: jdbc:mysql://localhost:3311/spring_security
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
